Make l2 block parsing be compatible with ecotone attributes
testinprod-io/op-fast-sync pull request #5
Opened 2024-04-14 06:51 UTC by mininny

In the ecotone release, L1 attributes in the transaction data is updated with different calldata layout: [ref](https://specs.optimism.io/protocol/deposits.html#l1-attributes---ecotone)

To make the payload builder be compatible with this new layout, this PR fixes the code to properly fetch the L1 block from the L2 transaction data.

2024-05-09 08:23 UTC, ImTei requested changes

2024-05-09 08:23 UTC, ImTei commented on apply_batch.py
> +        send_json_rpc(self.engine_url, f'engine_newPayloadV{2 if is_canyon else 1}', params=payload, token=self.jwt_token)
we have to use newPayloadV3 for Ecotone, and FCUV3 as well

2024-05-09 08:23 UTC, ImTei commented on build_payloads.py
> +        self.ecotone_block_number = ecotone_block_number
Superchain uses timestamp for hard forks. So ecotone_time should be better.

2024-05-09 08:23 UTC, ImTei commented on build_payloads.py
> +        payloadArray = [payload, [], l2_block['parentBeaconBlockRoot']]
parentBeaconBlockRoot is only for Ecotone.

2024-05-26 08:46 UTC, mininny commented on apply_batch.py
> +        send_json_rpc(self.engine_url, f'engine_newPayloadV{2 if is_canyon else 1}', params=payload, token=self.jwt_token)
i fixed to use correct api version. Also applied changes from your other comments as well 👍

2024-05-27 00:32 UTC, ImTei approved these changes

2024-06-08 09:20 UTC, merged